spring:
  application:
    name: umc

  config:
    import: "file:./.env[.properties]"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY}
    expiration:
      access: 1800000 # 30분
      refresh: ${JWT_TOKEN_EXPIRATION_REFRESH} # 14일
vote:
  deadline-seconds: ${VOTE_DEADLINE_SECONDS:90}
